services:
  nginx:
    image: nginx:1.26.1-alpine
    container_name: nginx-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - E:\WWW:/var/www
      - E:\Gopath\src\ptah-craft\Web:/var/ptah-craft/Web
    depends_on:
      - php74
      - php81
    links:
      - php74
      - php81
    restart: always

  php74:
    build:
      context: .
      dockerfile: DockerfilePHP74
    image: php:7.4-fpm
    container_name: php74
    volumes:
      - E:\WWW:/var/www
    restart: always

  php81:
    build:
      context: .
      dockerfile: DockerfilePHP81
    image: php:8.1-fpm
    container_name: php81
    volumes:
       - E:\WWW:/var/www
    restart: always