services:
  nginx:
    image: nginx:1.26.1-alpine
    container_name: nginx-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - E:\WWW:/var/www
      - E:\Gopath\src\ptah-craft\Web:/var/ptah-craft/Web
    depends_on:
      - php74
      - php82
    links:
      - php74
      - php82
    restart: always

  php74:
#    build:
#      context: .
#      dockerfile: DockerfilePHP74
    image: qianjing/php:7.4-fpm
    container_name: php74
    volumes:
      - E:\WWW:/var/www
    restart: always

  php82:
#    build:
#      context: .
#      dockerfile: DockerfilePHP82
    image: qianjing/php:8.2-fpm
    container_name: php82
    volumes:
       - E:\WWW:/var/www
    restart: always